# live/telemetry/us-east-1/<env>/_singletons/shared/cloudfront-logs/000/terragrunt.hcl
#
# Centralized CloudFront standard-access-logging DESTINATION bucket unit.
#
# Provisions the SSE-S3 (AES256), ACL-enabled S3 bucket that the collector-ingestion
# reference (v1.0.2) REQUIRES via its access_log_bucket_name input. CloudFront standard
# (legacy) logging writes log files into this bucket as the CloudFront log-delivery
# canonical user, which mandates:
#   - SSE-S3 (AES256) server-side encryption (NOT a customer KMS CMK; CloudFront log
#     delivery rejects an SSE-KMS destination).
#   - ACLs ENABLED via ObjectOwnership = BucketOwnerPreferred, with FULL_CONTROL granted
#     to the CloudFront log-delivery canonical user.
#   - same account, same region (us-east-1).
#
# This unit carries NO terraform.source: the generate "cloudfront_logs_bucket" block below
# emits the root-module .tf into the unit working directory, and the root.hcl-generated
# provider_generated.tf / versions_generated.tf / backend.tf complete the module. A unit
# with no source is (correctly) skipped by the pinned-source guard -- there is no module to
# pin, and providers/aws/** is frozen so no released module can build this bucket.
#
# The resource spec MIRRORS the proven, applied CloudFront-logging destination in the
# collector-ingestion EXAMPLE fixture (providers/aws/references/collector-ingestion/
# examples/default/main.tf, the access_logs bucket): block-public-access ON, versioning ON,
# BucketOwnerPreferred ownership, the owner + CloudFront-canonical-user + S3-LogDelivery
# ACL grants, AES256 SSE, and SELF server-access-logging (AWS-0089: a terminal log target
# logs to itself -- no trivy suppression).
#
# IDENTITY (D31): byte-for-byte identical between sandbox and prod. The bucket name is the
# only env-varying value and it derives from the namespace
# (include.root.locals.namespace_dns) -- no account id, region, or env literal appears in
# the generated config (namespace-derived-names law; tg-no-hardcoded-identity clean). The
# region/account come from the AWS provider (generated by root.hcl) and data sources.
#
# ACCOUNT GUARD (D2/D4): the root terragrunt.hcl generates the AWS provider with
# allowed_account_ids = ["${aws_account_id}"] derived from account.hcl. A wrong-profile
# apply fails fast.
#
# STATE PREREQUISITE (D40): the root remote_state block fails closed if the env state
# backend does not exist. Run the state-bootstrap unit first.
#
# spec 02 Section 4.2, ledger D2, D4, D31, D40, D45, D47.

include "root" {
  path           = find_in_parent_folders("root.hcl")
  expose         = true
  merge_strategy = "deep"
}

locals {
  # S3 is "_"-hostile -> use the flattened namespace_dns form for the bucket name.
  # namespace_dns already carries the "cloudfront-logs" service field, so it IS the
  # bucket name verbatim (no extra suffix -- that would both duplicate the token and
  # push the name past the 63-char S3 limit). The namespace_dns differs per env
  # (telemetry-useast1-prod-shared-cloudfront-logs-000 vs
  # telemetry-useast1-sandbox-shared-cloudfront-logs-000), so the bucket name is
  # set-scoped and collision-free by construction. No account id / region / env literal
  # appears here (D31, namespace-derived-names law).
  bucket_name = include.root.locals.namespace_dns
}

# ---------------------------------------------------------------------------
# Root-module generation: the CloudFront standard-logging DESTINATION bucket.
#
# Mirrors the collector-ingestion example fixture access_logs bucket spec exactly so
# the CloudFront/S3 logging wiring on the collector distribution has a correctly
# configured destination to write into. force_destroy keeps the whole env stack
# destroy/recreate-able from terragrunt alone (matches the data-lake unit, D31).
# ---------------------------------------------------------------------------
generate "cloudfront_logs_bucket" {
  path      = "cloudfront_logs_bucket.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # GENERATED by the cloudfront-logs terragrunt unit. Do not edit by hand.
    # Centralized CloudFront standard-access-logging destination bucket.

    data "aws_canonical_user_id" "current" {}
    data "aws_cloudfront_log_delivery_canonical_user_id" "current" {}

    resource "aws_s3_bucket" "cloudfront_logs" {
      bucket        = "${local.bucket_name}"
      force_destroy = true

      tags = { Name = "${local.bucket_name}" }
    }

    resource "aws_s3_bucket_public_access_block" "cloudfront_logs" {
      bucket                  = aws_s3_bucket.cloudfront_logs.id
      block_public_acls       = true
      block_public_policy     = true
      ignore_public_acls      = true
      restrict_public_buckets = true
    }

    resource "aws_s3_bucket_versioning" "cloudfront_logs" {
      bucket = aws_s3_bucket.cloudfront_logs.id

      versioning_configuration {
        status = "Enabled"
      }
    }

    # ACLs must be ENABLED (BucketOwnerPreferred) so CloudFront standard logging can write
    # as the CloudFront log-delivery canonical user. BucketOwnerEnforced (ACLs off) rejects
    # the grant with AccessControlListNotSupported.
    resource "aws_s3_bucket_ownership_controls" "cloudfront_logs" {
      bucket = aws_s3_bucket.cloudfront_logs.id

      rule {
        object_ownership = "BucketOwnerPreferred"
      }
    }

    resource "aws_s3_bucket_acl" "cloudfront_logs" {
      bucket = aws_s3_bucket.cloudfront_logs.id

      access_control_policy {
        owner {
          id = data.aws_canonical_user_id.current.id
        }

        # Bucket owner retains full control.
        grant {
          grantee {
            id   = data.aws_canonical_user_id.current.id
            type = "CanonicalUser"
          }
          permission = "FULL_CONTROL"
        }

        # CloudFront standard (legacy) logging writes as the CloudFront log-delivery
        # canonical user, which requires FULL_CONTROL on the destination bucket.
        grant {
          grantee {
            id   = data.aws_cloudfront_log_delivery_canonical_user_id.current.id
            type = "CanonicalUser"
          }
          permission = "FULL_CONTROL"
        }

        # S3 server access logging (this bucket's own self-logging) writes as the S3
        # LogDelivery group, which needs WRITE on the bucket and READ_ACP on the ACL.
        grant {
          grantee {
            type = "Group"
            uri  = "http://acs.amazonaws.com/groups/s3/LogDelivery"
          }
          permission = "WRITE"
        }

        grant {
          grantee {
            type = "Group"
            uri  = "http://acs.amazonaws.com/groups/s3/LogDelivery"
          }
          permission = "READ_ACP"
        }
      }

      depends_on = [
        aws_s3_bucket_ownership_controls.cloudfront_logs,
        aws_s3_bucket_public_access_block.cloudfront_logs,
      ]
    }

    # Log destination buckets must use SSE-S3 (AES256); CloudFront standard logging and
    # S3 server access logging both reject a customer-managed KMS CMK.
    resource "aws_s3_bucket_server_side_encryption_configuration" "cloudfront_logs" {
      bucket = aws_s3_bucket.cloudfront_logs.id

      rule {
        apply_server_side_encryption_by_default {
          sse_algorithm = "AES256"
        }
        bucket_key_enabled = true
      }
    }

    # AWS-0089: this terminal log-destination bucket records its OWN server access logs
    # under a dedicated prefix (an S3 bucket may be its own log target), exactly like the
    # state-bootstrap access-log bucket and the example fixture access_logs bucket. NO
    # trivy suppression.
    resource "aws_s3_bucket_logging" "cloudfront_logs" {
      bucket        = aws_s3_bucket.cloudfront_logs.id
      target_bucket = aws_s3_bucket.cloudfront_logs.id
      target_prefix = "${local.bucket_name}/server-access/"

      depends_on = [aws_s3_bucket_acl.cloudfront_logs]
    }

    # The bucket NAME is the contract consumed by the collector-ingestion unit's
    # access_log_bucket_name input. It is the namespace-derived static string (not a
    # data-source value) so the consumer can wire it via terragrunt dependency.
    output "cloudfront_logs_bucket_name" {
      description = "Name of the CloudFront standard-access-logging destination bucket."
      value       = aws_s3_bucket.cloudfront_logs.bucket
    }
  EOF
}
