# live/telemetry/us-east-1/<env>/_singletons/dns_owner/dns-delegation/000/terragrunt.hcl
#
# Root DNS-owner account (<dns-owner-account>) qa dns-delegation unit.
# Writes the NS delegation record for qa.telemetry.example.com
# into the DNS-owner zone (telemetry.example.com) via the
# primitives/route53-record primitive module. Sources exactly ONE module per AC-2.
#
# ACCOUNT GUARD (D2/D4):
# The root terragrunt.hcl generates the AWS provider with
#   allowed_account_ids = ["${local.aws_account_id}"]
# where aws_account_id is derived from the directory basename via account.hcl (D2).
# The root account id is <dns-owner-account>. A wrong-profile apply fails fast because
# the active caller identity will not match the allowed account (D4).
#
# BASE PROVIDER (D4):
# This unit runs in the root DNS-owner account (<dns-owner-account>), which also owns the
# DNS-owner zone. The base AWS provider generated by root terragrunt.hcl already
# authenticates to this account, so no secondary aliased provider or assume_role
# block is required (D4: the OIDC-assumed deploy role IS the deploy identity).
#
# RECORD CONTRACT (AC-2, AC-4, spec FR-2):
# This unit writes EXACTLY ONE NS record delegating qa.telemetry.example.com
# from the DNS-owner zone. The name_servers values come from
# dependency.dns_prod_zone.outputs.name_servers via a five-dotdot cross-account
# dependency (spec D-3). No hardcoded NS literals (AC-7).
#
# COLLAPSED APEX (spec section 1.1, D-5):
# For qa, dns_pretty_apex = dns_service_apex = "qa.telemetry.example.com".
# The NS record name is therefore the qa service apex itself (no prod-style
# "prod." prefix -- qa is delegated as a single flat subdomain).
#
# DNS-OWNER ZONE (D38, AC-1):
# zone_id is sourced exclusively from dns_owner_zone_id, resolved in the locals block
# directly from common/accounts.json (the is_dns_owner account) anchored on
# get_repo_root() (D3, D38). root.hcl is NOT read standalone here (same pattern as
# the prod dns-delegation unit to preserve the copy-any-level property).
#
# DEPENDENCY PLACEMENT (Terragrunt v1.x constraint):
# The cross-account dependency block lives HERE in terragrunt.hcl rather than in
# service_instance.hcl. root.hcl reads service_instance.hcl via read_terragrunt_config
# at line 40 in its own locals block; a dependency block in service_instance.hcl at
# that point causes cascade backend-init errors before mock_outputs can be served.
# Placing the block in the leaf terragrunt.hcl (evaluated in leaf context, not root
# context) prevents the cascade while keeping mock_outputs fully functional for
# offline validate/plan/init/destroy.
#
# spec section 4.2, 4.4, 1.1, 1.2, ledger D-3, D-5, D31, AC-2, AC-3, AC-4, AC-7.

include "root" {
  path           = find_in_parent_folders("root.hcl")
  expose         = true
  merge_strategy = "deep"
}

terraform {
  # Toggle-driven source (spec Section 4.3):
  # use_pinned_module_sources=false (qa/root): in-repo local source via get_repo_root().
  # use_pinned_module_sources=true (prod): pinned immutable git URL with ?ref= tag.
  source = local.account_vars.locals.use_pinned_module_sources ? "${include.root.locals.module_git_base}//providers/aws/primitives/route53-record?ref=providers/aws/primitives/route53-record/v1.0.0" : "${get_repo_root()}//providers/aws/primitives/route53-record"
}

# ---------------------------------------------------------------------------
# Cross-account dependency: qa dns-prod-zone unit (spec D-3, D31, AC-3)
#
# config_path is relative from THIS file's directory to the qa dns-prod-zone/000
# unit directory in the resolved service account (five levels up to us-east-1/, then into
# the qa account subtree).
#
# Relative path breakdown:
#   From: terragrunt/live/telemetry/us-east-1/<env>/_singletons/dns_owner/dns-delegation/000/
#   Up 5: terragrunt/live/telemetry/us-east-1/
#   To:   terragrunt/live/telemetry/us-east-1/bootstrap/<role>/dns-prod-zone/000/  (foundation tier)
#
# mock_outputs allow plan/validate/init/destroy to run offline before the qa
# dns-prod-zone unit is applied. The name_servers mock returns valid placeholder
# NS record values consistent with a real Route53 delegated zone.
#
# mock_outputs_allowed_terraform_commands restricts mocks to offline commands --
# apply never uses mocks (fail closed on apply, D31, AC-3).
# ---------------------------------------------------------------------------

dependency "dns_prod_zone" {
  config_path = "../../../../../bootstrap/${local.bootstrap_role}/dns-prod-zone/${local.dns_prod_zone_active}"

  mock_outputs_allowed_terraform_commands = ["validate", "plan", "init", "destroy"]
  mock_outputs = {
    name_servers = [
      "ns-mock-1.awsdns-01.com.",
      "ns-mock-2.awsdns-02.net.",
      "ns-mock-3.awsdns-03.org.",
      "ns-mock-4.awsdns-04.co.uk."
    ]
    zone_id = "ZMOCKQAZONEID1"
  }
}

# ---------------------------------------------------------------------------
# locals: account identity, dns_owner_zone_id, qa zone apex
# ---------------------------------------------------------------------------

locals {
  # Foundation-tier dns-prod-zone lives at bootstrap/<role>/ (a sibling of the env
  # subtree). bootstrap_role is derived from environment.hcl (never hardcoded, D31).
  bootstrap_role       = "${read_terragrunt_config(find_in_parent_folders("environment.hcl")).locals.environment}_role"
  dns_prod_zone_active = read_terragrunt_config("${get_terragrunt_dir()}/../../../../../bootstrap/${local.bootstrap_role}/dns-prod-zone/active.hcl").locals.active
  # Account-level locals for toggle-driven source resolution.
  account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl"))

  # dns_owner_zone_id is resolved here from common/ directly, NOT by reading root.hcl.
  # root.hcl cannot be read standalone via read_terragrunt_config(find_in_parent_folders("root.hcl")):
  # root.hcl's own find_in_parent_folders hierarchy reads resolve relative to root.hcl's
  # directory (terragrunt/) and abort parse. The common/ maps are anchored on get_repo_root()
  # (D3) so they resolve from any copied subtree depth, keeping the copy-any-level property
  # intact (spec section 4.8, D1, D3, D36, D38).

  # dns_owner_zone_id: the fail-fast-guarded zone id of the is_dns_owner account in
  # common/accounts.json (D38). The placeholder "<REAL_Z_ID>" or a missing/absent id
  # aborts parse with an actionable message.
  accounts              = jsondecode(file("${get_repo_root()}/terragrunt/common/accounts.json"))
  dns_owner_account_id  = [for acct_id, cfg in local.accounts : acct_id if lookup(cfg, "is_dns_owner", false) == true]
  dns_owner_entry       = length(local.dns_owner_account_id) > 0 ? local.accounts[local.dns_owner_account_id[0]] : tobool("ERROR: no account in common/accounts.json has is_dns_owner=true -- mark the DNS-owner account before deploying this scope.")
  dns_owner_zone_id_raw = lookup(local.dns_owner_entry, "dns_owner_zone_id", null)
  dns_owner_zone_id     = (local.dns_owner_zone_id_raw != null && local.dns_owner_zone_id_raw != "<REAL_Z_ID>") ? local.dns_owner_zone_id_raw : tobool("ERROR: dns_owner_zone_id in common/accounts.json is missing or contains the placeholder '<REAL_Z_ID>'. Replace <REAL_Z_ID> with the real Route53 hosted zone id for the dns-owner account before deploying.")

  # QA zone apex: resolved from common/domains.json keyed by "qa".
  # For qa, dns_service_apex = dns_pretty_apex = "qa.telemetry.example.com"
  # (collapsed apex, spec section 1.1, D-5). The NS delegation record name is the
  # qa service apex itself. The lookup fails fast if the env-class key is absent.
  environment_name = read_terragrunt_config(find_in_parent_folders("environment.hcl")).locals.environment
  domains          = jsondecode(file("${get_repo_root()}/terragrunt/common/domains.json"))
  domain_cfg       = lookup(local.domains, local.environment_name, null) != null ? local.domains[local.environment_name] : tobool("ERROR: env-class '${local.environment_name}' not found in common/domains.json -- add a row for this env-class before deploying.")
  qa_zone_apex     = local.domain_cfg["dns_service_apex"]
}

# ---------------------------------------------------------------------------
# inputs: route53-record primitive module (AC-2, spec FR-2)
#
# type = NS: this is the NS delegation record for qa.telemetry.example.com.
# name: the qa zone apex composed from domains.json (never hardcoded, AC-7).
# records: the qa zone name_servers from the cross-account dependency (D-3, AC-4).
#   No literal NS values are used -- they come exclusively from the dependency output.
# ttl: 172800 seconds (48 hours) -- standard TTL for NS delegation records.
# zone_id: the DNS-owner zone from local.dns_owner_zone_id (D38).
#
# The tags input uses include.root.locals.common_tags (not local.common_tags)
# because the root include block uses expose = true, making root locals
# accessible only via include.root.locals.<name> at leaf scope (spec 02).
# ---------------------------------------------------------------------------

inputs = {
  zone_id = local.dns_owner_zone_id
  name    = local.qa_zone_apex
  type    = "NS"
  ttl     = 172800
  records = dependency.dns_prod_zone.outputs.name_servers

  tags = include.root.locals.common_tags
}
