# live/telemetry/us-east-1/<env>/_singletons/shared/vpc-flow-logs/000/terragrunt.hcl
#
# VPC Flow Logs destination + delivery role unit.
#
# Provisions the KMS-encrypted CloudWatch log group and the IAM role that the
# collector-ingestion reference (v1.0.2, enable_flow_logs = true secure-by-default)
# REQUIRES via flow_logs_iam_role_arn + flow_logs_destination_arn. The composed
# vpc-network primitive creates the aws_flow_log consuming both by ARN
# (providers/aws/primitives/vpc/main.tf:49-55); it does NOT create them itself.
#
# This unit carries NO terraform.source: the generate "vpc_flow_logs" block below emits the
# root-module .tf into the unit working directory, and root.hcl's generated provider/
# versions/backend complete the module. A no-source unit is (correctly) skipped by the
# pinned-source guard -- there is no module to pin, and providers/aws/** is frozen.
#
# RESOURCES (mirrors the collector-ingestion example fixture flow-logs prerequisite,
# examples/default/main.tf aws_cloudwatch_log_group.flow_logs + aws_iam_role.flow_logs,
# improved with a least-privilege inline delivery policy):
#   - aws_cloudwatch_log_group: KMS-encrypted with the telemetry-data CMK (lake CMK), so
#     flow-log records are encrypted at rest (D10). The lake CMK policy already grants
#     logs.<region>.amazonaws.com for every log group in this account/region (ArnLike
#     EncryptionContext), so no KMS policy change is required.
#   - aws_iam_role: trusts vpc-flow-logs.amazonaws.com.
#   - aws_iam_role_policy: least-privilege CloudWatch publish (CreateLogStream,
#     PutLogEvents, DescribeLog*) scoped to the flow-log group ARN so the role can actually
#     deliver records (the fixture omitted this; real delivery needs it).
#
# IDENTITY (D31): byte-for-byte identical between sandbox and prod. The CMK ARN flows from
# the data-lake dependency output; the log-group + role names derive from the namespace. No
# account id, region, or env literal appears as a static literal in the generated config
# (namespace-derived-names law; tg-no-hardcoded-identity clean).
#
# DEPENDENCY (D37): consumes lake_kms_key_arn from the data-lake unit -- never recomputed.
#
# STATE PREREQUISITE (D40): the root remote_state block fails closed if the env state
# backend does not exist. Run state-bootstrap first.
#
# spec 02 Section 4.2, ledger D2, D4, D10, D31, D37, D40, D45, D47.

include "root" {
  path           = find_in_parent_folders("root.hcl")
  expose         = true
  merge_strategy = "deep"
}

dependency "data_lake" {
  config_path = "../../data-lake/${local.svc_instance}"

  # mock_outputs allow plan/validate to run before data-lake is applied; on apply the real
  # CMK ARN is used (fail closed, D31, AC-9). The mock ARN is derived from the resolved
  # region/account locals so a copied unit presents a mock for its own scope (AC-13).
  mock_outputs_allowed_terraform_commands = ["plan", "validate"]
  mock_outputs = {
    lake_kms_key_arn = "arn:aws:kms:${local.region}:${local.aws_account_id}:key/mock-lake-kms-key-id"
  }
}

locals {
  # Instance-relative local so a copied unit wires its sibling dependency at the new index
  # with zero edits (spec section 4.4).
  svc_instance = basename(get_terragrunt_dir())

  account_vars   = read_terragrunt_config(find_in_parent_folders("account.hcl"))
  aws_account_id = local.account_vars.locals.aws_account_id
  region         = include.root.locals.region

  # namespace_dns (flattened "_"->"-") drives the role name; namespace drives the log-group
  # path. Both are set-scoped and collision-free per env (D31, namespace-derived-names law).
  namespace     = include.root.locals.namespace
  namespace_dns = include.root.locals.namespace_dns

  # IAM role name <=64 chars; namespace_dns (47) + "-role" = 52. Log group under /vpc/.
  flow_logs_role_name      = "${local.namespace_dns}-role"
  flow_logs_log_group_name = "/vpc/${local.namespace}/flow-logs"

  # Flow-log group ARN (region/account-derived) for scoping the role inline policy. The :*
  # suffix covers every log stream in the group.
  flow_logs_log_group_arn = "arn:aws:logs:${local.region}:${local.aws_account_id}:log-group:${local.flow_logs_log_group_name}:*"
}

# ---------------------------------------------------------------------------
# Root-module generation: KMS-encrypted flow-log CloudWatch group + delivery role.
# The telemetry-data CMK ARN is interpolated from the data-lake dependency output (D37).
# ---------------------------------------------------------------------------
generate "vpc_flow_logs" {
  path      = "vpc_flow_logs.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # GENERATED by the vpc-flow-logs terragrunt unit. Do not edit by hand.
    # VPC Flow Logs destination (KMS-encrypted CloudWatch group) + delivery role.

    resource "aws_cloudwatch_log_group" "flow_logs" {
      name              = "${local.flow_logs_log_group_name}"
      retention_in_days = 365
      kms_key_id        = "${dependency.data_lake.outputs.lake_kms_key_arn}"

      tags = { Name = "${local.flow_logs_log_group_name}" }
    }

    resource "aws_iam_role" "flow_logs" {
      name = "${local.flow_logs_role_name}"

      assume_role_policy = jsonencode({
        Version = "2012-10-17"
        Statement = [
          {
            Sid       = "AllowVpcFlowLogsAssumption"
            Effect    = "Allow"
            Principal = { Service = "vpc-flow-logs.amazonaws.com" }
            Action    = "sts:AssumeRole"
          }
        ]
      })

      tags = { Name = "${local.flow_logs_role_name}" }
    }

    # Least-privilege CloudWatch publish scoped to the flow-log group (the fixture omitted
    # this; VPC Flow Logs delivery to CloudWatch needs it). Resource is the group ARN.
    resource "aws_iam_role_policy" "flow_logs" {
      name = "${local.flow_logs_role_name}-publish"
      role = aws_iam_role.flow_logs.id

      policy = jsonencode({
        Version = "2012-10-17"
        Statement = [
          {
            Sid    = "VpcFlowLogsCloudWatchPublish"
            Effect = "Allow"
            Action = [
              "logs:CreateLogStream",
              "logs:PutLogEvents",
              "logs:DescribeLogGroups",
              "logs:DescribeLogStreams",
            ]
            Resource = "${local.flow_logs_log_group_arn}"
          }
        ]
      })
    }

    # ARNs consumed by the collector leaf's flow_logs_iam_role_arn +
    # flow_logs_destination_arn inputs (the module validates them ^arn:aws:iam: / ^arn:aws:).
    output "flow_logs_iam_role_arn" {
      description = "ARN of the VPC Flow Logs delivery IAM role."
      value       = aws_iam_role.flow_logs.arn
    }

    output "flow_logs_destination_arn" {
      description = "ARN of the KMS-encrypted CloudWatch log group receiving VPC Flow Logs."
      value       = aws_cloudwatch_log_group.flow_logs.arn
    }
  EOF
}
